### ISSUE TITLE
Example Issue 

### ISSUE THREAD

**Issue by Chaosfuchs** [Chaosfuchs/capstone-project#1]
### Value description/ definition
As a < user >
I want to <save something, do something>
so that < reason why i will do this >
(make little Steps for Userstorys!)

### Description
Wireframe, Design Figma, or else
(add a picture) <img src='abc' width="...">
everything what can happen visually should be here!

### Acceptance criteria

- [ ] for example: the input must be 'required'
- [ ] for example: max-length must 100 characters or less
- [ ] for example: text should wrap on space characters
- [ ] for example:  text should scroll, whitespace should be trimmed, list should scroll behind the form

### Tasks

- [ ] Create a branch
- [ ] Make first Commit for Upstream (Create new branch for <feature>)
- [ ] Create component 'Componentname'
- [ ] Check on a real device (via Vercel for example)
- [ ] Workingsteps...

### Complexity
low, medium, high
