### ISSUE TITLE
App Logo

### ISSUE THREAD

**Issue by Chaosfuchs** [Chaosfuchs/capstone-project#11]
### Value description/ definition
As a user
I want to see a Logo in the upper left corner of the App
so that I know, that I use the right App

### Description
Put a customized logo in the upper left corner of the header
<img width="300" alt="Screenshot 2022-05-30 at 11 11 04" src="https://user-images.githubusercontent.com/102142386/170958897-24be330d-a3d1-47e2-a539-40220cffee84.png">

### Acceptance criteria
- [x] see the App logo in the upper left corner of the header
- [x] the logo must be visible on all pages header

### Tasks
- [x] Create a branch
- [x] Make first Commit for Upstream
- [x] put the logo in the header and style it, so that it fits

### Complexity
low
