### ISSUE TITLE
Dice Component on Home-Page

### ISSUE THREAD

**Issue by Chaosfuchs** [Chaosfuchs/capstone-project#12]
### Value description/ definition
As a user
I want to use execute random events
so that I can execute random events in my Rollplay-Round

### Description
<img width="300" alt="Screenshot 2022-05-30 at 11 13 43" src="https://user-images.githubusercontent.com/102142386/170959783-1b5c7244-346c-4dca-a7f1-eba49cce3ec8.png">

### Acceptance criteria

- [x] I can choose a dice from the dropdown field I want
- [x] Dice rolls on button
- [x] I can see the result of my rolled dice
- [x] I have at least 5 dices to choose from

 
### Tasks

- [x] Create a branch
- [x] Make first Commit for Upstream
- [x] Create component 'dice'
- [x] Create logic behind the dice-component
- [x] Make different dices in the code addible with 'useStore'

### Complexity
high

**Comment by F-Kirchhoff** [comment]
Hey Kerstin, very nice! I would say you can keep it as it is, with one execption:
- You can write down your tasks in more detail: I guess there will be more components than just a dice component, since you have the inputs and buttons around it as well. So the blue part in the wireframe is its own component. You should reflect that in the tasks.

Thats it, no more nit-picky remarks from me :D
