### ISSUE TITLE
Customize styling and cleaning Code

### ISSUE THREAD

**Issue by Chaosfuchs** [Chaosfuchs/capstone-project#13]
### Value description/ definition
As a user
I want to have a pretty app with a cool design
so that I'm happy to use this app

### Description
no Wireframe for this.

### Acceptance criteria

- [x] all texts must be easy readable
- [x] all buttons must be big enough to click easily
- [x] the colors must be harmonized, so that texts and components are easy to read
- [x] layout need to fit to the device
- [x] all suggestions are processed and implemented from earlier reviews

### Tasks

- [x] customize the styling of the app
- [x] clean the code

### Complexity
low
