### ISSUE TITLE
Picture Upload on Character-Sheet

### ISSUE THREAD

**Issue by Chaosfuchs** [Chaosfuchs/capstone-project#17]
### Value description/ definition
As a user
I want to upload a picture of my character
so that I can see how my character looks like

### Description
<img width="700" alt="UserStory8" src="https://user-images.githubusercontent.com/102142386/171410345-8e5af2b6-5962-4e8b-9ffc-27711c0033d3.png">

### Acceptance criteria

- [x] I need to have a field where I can click to upload an Image
- [x] It need be possible to upload a Image from my Device/ Computer/ Handy
- [x] Image needs to be stored in the useStore in the 'characters-Array'

### Tasks

- [x] Create a branch
- [x] Make first Commit for Upstream
- [x] Create a field on my 'AddForm' for upload an Image
- [x] Create a field on my 'ShowCharacter' Component where the Image will display on the sheet
- [x] Put the logic for the image upload behind

### Complexity
high

**Comment by CJAkkuec** [comment]
A couple of notes: I'd probably include that the image is saved "somewhere" (whichever storage/upload option you choose, such as Cloudinary/etc) in your acceptance criteria, as well as the requires steps in your tasks. I'd suggest that the complexity may actually be high rather than medium/high in terms of how much time I'd set aside for it. :)
