### ISSUE TITLE
Create Character, save and show it on other Page

### ISSUE THREAD

**Issue by Chaosfuchs** [Chaosfuchs/capstone-project#2]
### Value definition
As a User, I want to create a new character in a form, so that I can write down my informations for my new Character and can save it or reset the form.

### Description
<img width="500" alt="UserStory1" src="https://user-images.githubusercontent.com/102142386/169257171-b51fcf50-2435-46a0-b20f-c4e34290cc2c.png">

### Acceptance criteria
- [x] The inputs must be 'required'
- [x] max-length for input 1 must 20 characters or less
- [x] max-length for input 2 must 255 characters or less
- [x] Buttons must be clickable
- [x] Buttons must have a hover effect to show that their clickable
- [x] Buttons font must be readable
- [x] Save-Button must save the text if clicked and
- [x] text must be show on the character page when form is saved
- [x] text should wrap on space characters
- [x] text should scroll if larger than view
- [x] Reset-Button must clear the whole form

### Tasks
- [x] Create a new branch
- [x] Create and push a first commit for upstream
- [x] Create a form with two inputs ( 1 Text, 1 Textarea)
- [x] Create two buttons under the form (1 Save, 1 Reset)
- [x] Create an Area on the Character Page for the view, when the form is saved
- [x] Create a on Click function that puts the text from the form to the Showing-Page (Characters Page)
- [x] Create a on Click function to clear the form

### Complexity
high

**Comment by CJAkkuec** [comment]
Hey there! Impressive that you already created your first user story! I have a little bit of feedback, though. Also - this wouldn't actually be your first user story in terms of what you start with.

**A general note:**
You wouldn't actually start with a home page and navigation. At present, you can't meet your own acceptance criteria, because there isn't anything to navigate TO yet. I understand the want to start with the page you see first when you open the app, but instead you'd start with your core feature: the character form. Your first concern is getting data to display. If you're ever wondering where to start: it's all in the abbreviation CRUD. ;)
_The idea is that every user story is supposed to provide the user with a fully functioning app._ Obviously, the first version of your app (after the first user story is done) will be very limited in what it can actually do, but that's how you'd want to go about it. Hence the note about starting with the form first, because that's something the user can actually use once it's done. If that's not super clear yet, we can talk about it a little more.

Here are a couple more specific notes:

> "As a Roleplayer
> I want to open the App and see the possibilities to navigate through the App and can click a button to switch the Page, so that I can switch to the Page I prefer to see/ use."

I think replacing User with Roleplayer is a cute idea, but strictly speaking, that's something you wouldn't necessarily change. It's not wrong, just unusual. I would perhaps shorten the sentence following, like so: "As a Roleplayer, I want to see a home page when I start the app, as well as a navigation I can easily access." Something like that, as short and concise as you can make it.

> (the Button "Dice" is not relevant for now!)

No need to include it then. ;) As far as user stories, code reviews, QA, etc are concerned - don't include things that aren't part of the feature, don't commit commented out code, and so on.

Do you perhaps have any acceptance criteria for the home page as well? Maybe something to do with accessibility, being able to see everything, ...

Regarding the tasks, there's differing opinions regarding whether or not to include steps such as "create a branch"/etc as part of your tasks. I suppose it's up to you whether you want to be as specific, but personally I don't think it's absolutely necessary. It can be assumed that that would be your starting point, and so on. If you want to include it, feel free to do so, though! :)

Don't get discouraged by how nit-picky I'm being, it's still all part of the learning process! <3

**Comment by Chaosfuchs** [comment]
I have switch my first two UserStorys, to have in Story 1 a MVP and update it in the Wireframes and a little bit in the information details!

**Comment by Chaosfuchs** [comment]
closed #4
