### ISSUE TITLE
Character limit

### ISSUE THREAD

**Issue by Chaosfuchs** [Chaosfuchs/capstone-project#21]
### Value description/ definition
As a user
I want to see how much characters I can write in the Informationfield
so that I know how much text I can write

### Description
<img width="300" alt="UserStory9" src="https://user-images.githubusercontent.com/102142386/172337413-096d48eb-b419-4190-bcac-117ce25d0e94.png">

### Acceptance criteria

- [ ] I can see how much characters left for writing
- [ ] The counter must update after each character

### Tasks

- [ ] Create a branch
- [ ] Make first Commit for Upstream
- [ ] Create 'counter' for characters
- [ ] Put the functionality behind the counter

### Complexity
medium
