### ISSUE TITLE
Animations

### ISSUE THREAD

**Issue by Chaosfuchs** [Chaosfuchs/capstone-project#22]
### Value description/ definition
As a user
I want to see a cool animation on the dice
so that I can see when it rolls

### Description
<img width="300" alt="UserStory10" src="https://user-images.githubusercontent.com/102142386/172341905-c2fdb8ae-e263-4191-9824-a563406ae5bd.png">

### Acceptance criteria

- [x] an animation should be visible if the roll button was clicked

### Tasks

- [x] Create a branch
- [x] Make first Commit for Upstream
- [x] studying the framer library for animation, reading the documentation
- [x] implement an animation in the 'dice component'

### Complexity
large

**Comment by CJAkkuec** [comment]
I'm not sure if I'd advise including 'research' as a task. I'd rather suggest including the sort of library you've decided on using. I'd probably guesstimate that the complexity might be medium to large, depending on how complex you need/want the animation to be.

Also, something to think about: at what point during the animation is the final result displayed?
