### ISSUE TITLE
Specified View of Sheets

### ISSUE THREAD

**Issue by Chaosfuchs** [Chaosfuchs/capstone-project#24]
### Value description/ definition
As a user 
I want to see my characters in a List with Name and Type of the Roleplay,
so that I can choose, wich I want to see in full View with all details.

### Description
<img width="1000" alt="UserStory11" src="https://user-images.githubusercontent.com/102142386/172408046-05a0bfce-b2ca-4c4e-a566-387d50ec6248.png">

### Acceptance criteria

- [x] I need a Inputfield where I can write down, what kind of role play my character belongs to
- [x] the Sheet needs to be shown only with 'Name' and 'Type of Roleplay' in the Overview
- [x] when I click on a character it needs to open the Charactersheet with its full details and the options

### Tasks

- [x] Create a branch
- [x] Make first Commit for Upstream 
- [x] Create Inputfield in form 'Type of Roleplay'
- [x] Create a 'Card Component' to display the Name and the Type only
- [x] Let the 'Show Card' by click overview with the details and the options for delete and edit
- [x] Create a 'Back-Button' on the Detailcard

### Complexity
high
