### ISSUE TITLE
Rework App-Styling

### ISSUE THREAD

**Issue by Chaosfuchs** [Chaosfuchs/capstone-project#26]
### Value description/ definition
As a user
I want to see a cool coherent design in which I can view all the features of the app wonderfully
so that I like to use this app

### Description
rework the styling and positioning of the objects on my view

### Acceptance criteria

- [ ] the design needs to be coherent in itself
- [ ] all colors match each other
- [ ] all components need to display correctly 

### Tasks

- [ ] Create a branch
- [ ] Make first Commit for Upstream
- [ ] rework the styling

### Complexity
low

**Comment by marcbendixen** [comment]
Hey 👋 looks good to me!
