### ISSUE TITLE
Add Picture View on Create Page

### ISSUE THREAD

**Issue by Chaosfuchs** [Chaosfuchs/capstone-project#27]
### Value description/ definition
As a user
I want to see wich image i want to upload
so that I know that it is the correct image I want to upload to my sheet

### Description
implement that the uploaded image is shown in the create form 

### Acceptance criteria

- [x] the images must shown correctly on the components

### Tasks

- [x] Create a branch
- [x] Make first Commit for Upstream
- [x] implement a view-space for the image

### Complexity
low

**Comment by marcbendixen** [comment]
Hey 👋 good idea!
The only thing I would add: what happens when the user added the wrong image? He should be able to delete it? Then you also need the functionality for that.
