### ISSUE TITLE
Database MongoDB/ Mongoose

### ISSUE THREAD

**Issue by Chaosfuchs** [Chaosfuchs/capstone-project#28]
### Value description/ definition
As a user
I want to save my created sheets for a long time
so that their always be there when I start the app

### Description
implement Database with MongoDB and Mongoose

### Acceptance criteria

- [x] created sheets need to save in the database 
- [x] I can see in Mongo DB the saved values
- [x] values need to delete from the database when delete in app
- [x] values need to edit in the database when edit in app

### Tasks

- [x] Create a branch
- [x] Make first Commit for Upstream 
- [x] implement Mongoose and MongoDB to the project
- [x] implement logic to edit and delete with database

### Complexity
high

**Comment by marcbendixen** [comment]
Hey 👋 this is a good feature. Keep in mind that this is not only about saving the sheets but also update and delete them 😉
