### ISSUE TITLE
Create Home Page and Navigation

### ISSUE THREAD

**Issue by Chaosfuchs** [Chaosfuchs/capstone-project#3]
### Value definition
As a User
I want to see a home page when I start the app, as well as a navigation I can easily access,
so that I can see what I can do and what pages are there.

### Description
<img width="300" alt="UserStory2" src="https://user-images.githubusercontent.com/102142386/169253477-0fe613f7-d00e-4f2d-962f-97773965aa77.png">

### Acceptance criteria

- [x] The buttons must be clicked and navigate to the right page
- [x] The buttons need to be big enough to click it on a mobile screen with the finger

### Tasks

- [x] Create a branch
- [x] Create and push first commit for upstream
- [x] Create `grid` for layout (Headline, Content, Navbar)
- [x] Create `Navbar-Component`
- [x] Create `Button-Components` on the Content section for the pages
- [x] Link the Buttons to the corresponding page
- [x] Copy and paste the Layout/ Navbar to all pages

### Complexity
medium

**Comment by Chaosfuchs** [comment]
Update the sequence of my first two Storys and update Wireframes and information details

**Comment by CJAkkuec** [comment]
A little note:

> Create Page files in project for navigating

The pages should already exist. This user story should only be about making sure to establish routing between the pages, etc. You wouldn't create empty pages to navigate to. If you only have your "create character" page and your "my character" page at the point of working on this user story, then those would be the only ones you'd include in your navigation for the time being - which is completely fine, by the way. You can expand upon that once you create your dice page, etc. :)

**Comment by Chaosfuchs** [comment]
Updated Tasks, delete "Create Page files in project for navigating" because no need!
