### ISSUE TITLE
Local Storage

### ISSUE THREAD

**Issue by Chaosfuchs** [Chaosfuchs/capstone-project#5]
### Value description/ definition
As a user 
I want to save my charactersheet that i added
so that it is still visible after reload.

### Description

no visual required

### Acceptance criteria

- [x] when refreshing the page, all entered informations are still there
- [x] the saved values are visible in the browser's local storage

### Tasks

- [x] Create new branch
- [x] Create file for local storage
- [x] Add logic to make local storage possible
- [x] check if it works, eventually on a real device

### Complexity
low

**Comment by irenepapaspyratos** [comment]
Hi Kerstin, are you sure, that you want to create 2 branches?

**Comment by Chaosfuchs** [comment]
Thanks for review my UserStory Irene, no I have forgot to delete these tasks. ^^'' 
I have updated it now.

**Comment by irenepapaspyratos** [comment]
😄Well, you could have left ONE branch in the tasks, but I guess your developer-team remembers to do this anyway.. 😉
