### ISSUE TITLE
Delete-Button on Charactersheets

### ISSUE THREAD

**Issue by Chaosfuchs** [Chaosfuchs/capstone-project#6]
### Value description/ definition
As a user 
I want to delete my written Charactersheets on the "My Charakters"-Page
so that I can delete my written sheets.

### Description
<img width="300" alt="Screenshot 2022-05-27 at 09 09 14" src="https://user-images.githubusercontent.com/102142386/170649987-37dc9628-f6e6-4085-8e41-e33906327220.png">

### Acceptance criteria
- [x] button needs to be big enough for mobile screen
- [x] button must delete the sheet if clicked

### Tasks
- [x]  Create a branch
- [x]  Make first Commit for Upstream 
- [x] create the `button` on the Sheet
- [x] create functionality for the `button`

### Complexity
low

**Comment by cat-miller** [comment]
looks good to me!
