### ISSUE TITLE
Edit-Button on Charactersheets

### ISSUE THREAD

**Issue by Chaosfuchs** [Chaosfuchs/capstone-project#8]
### Value description/ definition
As a user
I want to edit my saved Charactersheets
so that I can make changes when I want.

### Description
<img width="300" alt="Screenshot 2022-05-27 at 12 36 34" src="https://user-images.githubusercontent.com/102142386/170684025-cfe88763-11f6-40f9-b620-f0cc6d40a717.png">
<img width="300" alt="Screenshot 2022-05-27 at 14 44 02" src="https://user-images.githubusercontent.com/102142386/170701593-35cbd290-0f36-47ec-b184-ad69a24b6175.png">

### Acceptance criteria
- [x] button needs to be big enough for mobile screen
- [x] button must send the choosen charactersheet to the create-page for edit when clicked
- [x] User will send to "Create Character"-Page and the Side will change to "Edit Character"
- [x] Save-Button on Form should change to a "Update"-Button to save the changes

### Tasks
- [x]  Create a branch
- [x]  Make first Commit for Upstream 
- [x] create the `button` on the Sheet
- [x] create functionality for the `button`
- [x] Add functionality to change `Header` on create-Page when its in "update-mood"
- [x] Add functionality to change Save-Button Text to "Update" to show it is in "update-mood"

### Complexity
high

**Comment by marcbendixen** [comment]
Hey 👋 
in general I think that's good, maybe you could be a little more specific in some places. For example: if you send the user to the create-page, is the page still the same? Maybe the button there could be "Update" instead of "Save", or the title of the page could be "Update character" instead of "Create character". Then the user knows exactly that he is in "update-mode". Just a few ideas. The scope of the userstory is great 👍
