### ISSUE TITLE
Active Effect to Navbar-Buttons

### ISSUE THREAD

**Issue by Chaosfuchs** [Chaosfuchs/capstone-project#9]
### Value description/ definition
As a user
I want to see in the Navbar on wich page I am actually 
so that I exactly know on one look, on wich page I am

### Description
<img width="900" alt="Screenshot 2022-05-27 at 16 32 03" src="https://user-images.githubusercontent.com/102142386/170720418-a98ad52e-7bf7-4c79-ad2b-1f9dc5b846d7.png">

### Acceptance criteria
- [x] The buttons must change their color when the right page is showing

### Tasks
- [x] Create a branch
- [x] Make first Commit for Upstream
- [x] Create functionality on the buttons for when I have switched the page

### Complexity
medium

**Comment by marcbendixen** [comment]
Hey 👋 
in my opinion: even if it's clear what you mean, you could still show a wireframe. It can happen that someone doesn't know your project yet and so he/she doesn't have to look at other user stories. And because it's also an important visual part of your navigation 🙂 

apart from that everything is alright 👍
